### PR TITLE
Implement async contest manager interface on AsyncElasticsearch

### PR DESCRIPTION
**Pull request by albins**
Features:
- updated README with the new syntax (first example)
- test code in a separate file, because it has to use Python 3.5+ syntax

Closes: #48

### CODE REVIEW

**Comment by karmi** [comment]
Hi @albins, we have found your signature in our records, but it seems like you have signed with a different e-mail than the one used in yout Git [commit](https://github.com/elastic/elasticsearch-py-async/pull/49.patch). Can you please add both of these e-mails into your Github profile (they can be hidden), so we can match your e-mails to your Github profile?

**Comment by 3lnc** [comment]
Is this still WIP?

**Comment by albins** [comment]
@3lnc I had some trouble testing my changes (as in, writing the actual tests), but they are done otherwise! I'm removing the WIP tag.

**Comment by hampsterx** [comment]
hate to plus one but.. +1

**Comment by Pehat** [comment]
Nice feature, thank you! Ping @karmi one more time.

**Comment by karmi** [comment]
Cool, I see the checks are green now. @fxdgear or @HonzaKral , can you have a look at the PR?

**Pull request merged**
