### PR TITLE
Fixes issue #8

### PR DESCRIPTION
**Pull request by stickperson**
`self.log_request_fail` was missing the `url_path`.

### CODE REVIEW

**Comment by HonzaKral** [comment]
Thank you for the patch!

**Comment by stickperson** [comment]
No problem. Will a new version be released?

**Comment by HonzaKral** [comment]
Definitely, I will release a `5.0` version to keep up with the version numbers soon.

**Comment by HonzaKral** [comment]
Definitely, I will release a `5.0` version to keep up with the version numbers soon.

**Pull request merged**
