### PR TITLE
fix/ssl_context

### PR DESCRIPTION
**Pull request by quasiben**
adds `ssl_context` as optional parameter for handling certs

```python
sslcontext = ssl.create_default_context(cafile=ca_certs)
client = AsyncElasticsearch(
        hosts=[host],
        port=port,
        http_auth=(username, password),
        use_ssl=True,
        sslcontext=sslcontext
    )
```

### CODE REVIEW

**Comment by quasiben** [comment]
I have signed the CLA

**Comment by quasiben** [comment]
resolves #17

**Comment by HonzaKral** [comment]
Thank you for the PR @quasiben, can I ask why you prefer exposing the context parameter instead of doing `ssl.create_default_context(cafile=ca_certs)` in the `__init__` method, using the interface we already have?

Unless there is a direct reason I would prefer to keep the same interface.

Thanks again for the report and the quick fix!

**Comment by quasiben** [comment]
I suppose that would be ok.  I may have been influenced by the raw TCPConnectors inputs as demonstrated here: http://aiohttp.readthedocs.io/en/stable/client.html#ssl-control-for-tcp-sockets .  Since I'm somewhat unfamiliar in this area I just assume let the user define their own ssl_context.  For example, they may want to set `capath` and `cadata`.

As an aside, what are the intentions of `client_key` and `client_cert` in the current interface?  Are they place holders for something like an `ssl_context`?

**Comment by fxdgear** [comment]
This has been completed already.

**Pull request closed without merging**
