### PR TITLE
Add missing modules for SSL

### PR DESCRIPTION
**Pull request by jwaterhouse**
The SSL logic in connection.py is missing imports for ssl and warnings.

### CODE REVIEW

**Comment by HonzaKral** [comment]
These imports are not needed for the run of the module. Maybe I am missing something but this PR doesn't change the functionality in any way and just adds unneeded imports. I will close it but please feel to reopen with additional information. Thanks!

**Comment by jwaterhouse** [comment]
On master the `ssl` module gets used here: https://github.com/elastic/elasticsearch-py-async/blob/195e5ac7413689be996b9494f779dbe887518be0/elasticsearch_async/connection.py#L56

Not sure if this has changed in another branch.

**Comment by wowkin2** [comment]
Can you merge this Pull Request?
It is related to [issue](https://github.com/elastic/elasticsearch-py-async/issues/35) that I have with `warnings` module.

**Comment by id13** [comment]
Up ! In my case the absence of ssl import statement causes errors

**Comment by keunhong** [comment]
Bump

**Pull request merged**
